import json
import os
import sys
import logging
from seqeval.metrics import f1_score

# Add the project root to path so we can import your utils
sys.path.append(os.getcwd()) 

from seqeval.metrics import classification_report
from seqeval.scheme import IOB2
# Import your project's specific mapping logic
from src.utils.label_mapping import get_crossner_labels, collapse_to_coarse

logging.basicConfig(format="%(asctime)s | %(levelname)s | %(message)s", level=logging.WARNING)
logger = logging.getLogger(__name__)

def load_conll_data(file_path):
    sentences, labels = [], []
    current_sent, current_labs = [], []
    with open(file_path, 'r', encoding='utf-8') as f:
        for line in f:
            line = line.strip()
            if not line:
                if current_sent:
                    sentences.append(current_sent)
                    labels.append(current_labs)
                    current_sent, current_labs = [], []
                continue
            parts = line.split()
            current_sent.append(parts[0])
            current_labs.append(parts[-1])
    return sentences, labels

def load_json_predictions(file_path, label_list):
    """
    Loads JSON and maps integer IDs back to CrossNER string labels
    using the list generated by your get_crossner_labels() function.
    """
    with open(file_path, 'r', encoding='utf-8') as f:
        data = json.load(f)
    
    raw_preds = data["preds"]
    string_preds = []
    for sent_ids in raw_preds:
        # Map integer -> string label using index
        string_preds.append([label_list[idx] for idx in sent_ids])
    return string_preds

def get_entities_from_dataset(sentences, labels):
    entities = set()
    for sent, labs in zip(sentences, labels):
        current_ent = []
        for word, tag in zip(sent, labs):
            if tag.startswith('B-'):
                if current_ent: entities.add(" ".join(current_ent).lower())
                current_ent = [word]
            elif tag.startswith('I-'):
                current_ent.append(word)
            else:
                if current_ent: entities.add(" ".join(current_ent).lower())
                current_ent = []
        if current_ent: entities.add(" ".join(current_ent).lower())
    return entities

def split_seen_unseen(test_words, test_true, test_pred, seen_lexicon):
    s_true, s_pred = [], []
    u_true, u_pred = [], []

    for words, t_tags, p_tags in zip(test_words, test_true, test_pred):
        min_len = min(len(words), len(t_tags), len(p_tags))
        
        words, t_tags, p_tags = words[:min_len], t_tags[:min_len], p_tags[:min_len]

        st, sp = ["O"] * min_len, ["O"] * min_len
        ut, up = ["O"] * min_len, ["O"] * min_len
        
        i = 0
        while i < min_len:
            if t_tags[i].startswith('B-'):
                start = i
                etype = t_tags[i][2:]
                i += 1
                while i < min_len and t_tags[i] == f'I-{etype}':
                    i += 1
                end = i
                entity_text = " ".join(words[start:end]).lower()
                
                # Check if the entity string was in CoNLL Training
                if entity_text in seen_lexicon:
                    st[start:end], sp[start:end] = t_tags[start:end], p_tags[start:end]
                else:
                    ut[start:end], up[start:end] = t_tags[start:end], p_tags[start:end]
            else:
                i += 1
        s_true.append(st); s_pred.append(sp)
        u_true.append(ut); u_pred.append(up)
    return (s_true, s_pred), (u_true, u_pred)

# --- EXECUTION ---

# 1. Define Paths
TRAIN_PATH = "data/raw/conll2003/train.txt"
TEST_PATH = "data/raw/crossner/politics/test.txt"
PRED_PATH = "results/metrics/preds_dapt_20260511_224820.json"   # DAPT predictions
# PRED_PATH = "results/metrics/preds_crossner_20260511_165540.json"   # CROSSNER predictions

# 2. Load the mapping from your project
crossner_label_list = get_crossner_labels()

print("Loading data and mapping IDs...")
train_words, train_labs = load_conll_data(TRAIN_PATH)
test_words, test_labs = load_conll_data(TEST_PATH)
test_preds = load_json_predictions(PRED_PATH, crossner_label_list)

# 3. Collapse labels to coarse for a fair CoNLL comparison
# Since CoNLL doesn't know what a 'politician' is, we evaluate at the 'person' level
test_labs_coarse = [collapse_to_coarse(s) for s in test_labs]
test_preds_coarse = [collapse_to_coarse(s) for s in test_preds]

# 4. Perform Split
seen_entities = get_entities_from_dataset(train_words, train_labs)
seen_data, unseen_data = split_seen_unseen(test_words, test_labs_coarse, test_preds_coarse, seen_entities)

# Patch 2: print entity counts and ratio
seen_count   = sum(1 for seq in seen_data[0]   for tag in seq if tag.startswith("B-"))
unseen_count = sum(1 for seq in unseen_data[0] for tag in seq if tag.startswith("B-"))
total        = seen_count + unseen_count
print(f"\nSeen entities   : {seen_count:,}  ({seen_count/total:.1%})")
print(f"Unseen entities : {unseen_count:,}  ({unseen_count/total:.1%})")

print("\n--- RESULTS FOR SEEN ENTITIES (Coarse Level) ---")
print(classification_report(seen_data[0], seen_data[1], mode='strict', scheme=IOB2))

print("\n--- RESULTS FOR UNSEEN/EMERGING ENTITIES (Coarse Level) ---")
print(classification_report(unseen_data[0], unseen_data[1], mode='strict', scheme=IOB2))

# Patch 3: print F1 gap
seen_f1   = f1_score(seen_data[0],   seen_data[1],   mode='strict', scheme=IOB2)
unseen_f1 = f1_score(unseen_data[0], unseen_data[1], mode='strict', scheme=IOB2)
print(f"Seen F1: {seen_f1*100:.2f}  |  Unseen F1: {unseen_f1*100:.2f}  |  Gap: {(seen_f1 - unseen_f1)*100:+.2f}")

for i in range(3):
    print("Words :", test_words[i])
    print("True  :", test_labs_coarse[i])
    print("Pred  :", test_preds_coarse[i])
    print()